const axios = require('axios');
const mumaker = require('mumaker');

// Base channel info template
const channelInfo = {
    forwardingScore: 1,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid: '120363375814828971@newsletter',
        newsletterName: '𝗠𝗔𝗥𝗖𝗘𝗨𝗦𝗘-𝗫𝗠𝗗😈',
        serverMessageId: -1
    }
};

// Reusable message templates
const messageTemplates = {
    error: (message) => ({
        text: message,
        contextInfo: channelInfo
    }),
    success: (text, imageUrl) => ({
        image: { url: imageUrl },
        caption: "GENERATED BY 𝗠𝗔𝗥𝗖𝗘𝗨𝗦𝗘-𝗫𝗠𝗗😈",
        contextInfo: channelInfo
    })
};

async function textmakerCommand(sock, chatId, message, q, type) {
    try {
        if (!q) {
            return await sock.sendMessage(chatId, messageTemplates.error("Please provide text to generate\nExample: .metallic Nick"));
        }

        // Extract text
        const text = q.split(' ').slice(1).join(' ');

        if (!text) {
            return await sock.sendMessage(chatId, messageTemplates.error("Please provide text to generate\nExample: .metallic Nick"));
        }

        try {
            let result;
            switch (type) {
                case 'metallic':
                    result = await mumaker.ephoto("https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html", [text]);
                    break;
                case 'ice':
                    result = await mumaker.ephoto("https://en.ephoto360.com/ice-text-effect-online-101.html", [text]);
                    break;
                case 'snow':
                    result = await mumaker.ephoto("https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html", [text]);
                    break;
                case 'impressive':
                    result = await mumaker.ephoto("https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html", [text]);
                    break;
                case 'matrix':
                    result = await mumaker.ephoto("https://en.ephoto360.com/matrix-text-effect-154.html", [text]);
                    break;
                case 'light':
                    result = await mumaker.ephoto("https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html", [text]);
                    break;
                case 'neon':
                    result = await mumaker.ephoto("https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html", [text]);
                    break;
                case 'devil':
                    result = await mumaker.ephoto("https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html", [text]);
                    break;
                case 'purple':
                    result = await mumaker.ephoto("https://en.ephoto360.com/purple-text-effect-online-100.html", [text]);
                    break;
                case 'thunder':
                    result = await mumaker.ephoto("https://en.ephoto360.com/thunder-text-effect-online-97.html", [text]);
                    break;
                case 'leaves':
                    result = await mumaker.ephoto("https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html", [text]);
                    break;
                case '1917':
                    result = await mumaker.ephoto("https://en.ephoto360.com/1917-style-text-effect-523.html", [text]);
                    break;
                case 'arena':
                    result = await mumaker.ephoto("https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html", [text]);
                    break;
                case 'hacker':
                    result = await mumaker.ephoto("https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html", [text]);
                    break;
                case 'sand':
                    result = await mumaker.ephoto("https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html", [text]);
                    break;
                case 'blackpink':
                    result = await mumaker.ephoto("https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html", [text]);
                    break;
                case 'glitch':
                    result = await mumaker.ephoto("https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html", [text]);
                    break;
                case 'fire':
                    result = await mumaker.ephoto("https://en.ephoto360.com/flame-lettering-effect-372.html", [text]);
                    break;
                case 'incandescent':
                    result = await mumaker.ephoto("https://en.ephoto360.com/text-effects-incandescent-bulbs-219.html", [text]);
                    break;
                case 'gold':
                    result = await mumaker.ephoto("https://en.ephoto360.com/modern-gold-4-213.html", [text]);
                    break;
                case 'purple2':
                    result = await mumaker.ephoto("https://en.ephoto360.com/purple-text-effect-online-100.html", [text]);
                    break;
                case 'thor':
                    result = await mumaker.textpro("https://textpro.me/create-thor-logo-style-text-effect-online-1064.html", [text]);
                    break;
                case 'lightglow':
                    result = await mumaker.textpro("https://textpro.me/create-light-glow-sliced-text-effect-online-1068.html", [text]);
                    break;
                case 'whitegold':
                    result = await mumaker.textpro("https://textpro.me/elegant-white-gold-3d-text-effect-online-free-1070.html", [text]);
                    break;
                case 'cat':
                    result = await mumaker.textpro("https://textpro.me/write-text-on-foggy-window-online-free-1015.html", [text]);
                    break;
                case 'harrypotter':
                    result = await mumaker.textpro("https://textpro.me/create-harry-potter-text-effect-online-1025.html", [text]);
                    break;
                case 'transformer':
                    result = await mumaker.textpro("https://textpro.me/create-a-transformer-text-effect-online-1035.html", [text]);
                    break;
                case 'water':
                    result = await mumaker.ephoto("https://en.ephoto360.com/create-water-effect-text-online-295.html", [text]);
                    break;
                case 'devil2':
                    result = await mumaker.textpro("https://textpro.me/create-neon-devil-wings-text-effect-online-free-1014.html", [text]);
                    break;
                case 'greenneon':
                    result = await mumaker.textpro("https://textpro.me/green-neon-text-effect-874.html", [text]);
                    break;
                case 'neonlight':
                    result = await mumaker.textpro("https://textpro.me/create-glowing-neon-light-text-effect-online-free-1061.html", [text]);
                    break;
                case 'wall':
                    result = await mumaker.textpro("https://textpro.me/break-wall-text-effect-871.html", [text]);
                    break;
                case 'didong':
                    result = await mumaker.ephoto("https://ephoto360.com/tao-anh-che-vui-tu-choi-cuoc-goi-voi-ten-cua-ban-930.html", [text]);
                    break;
                case 'naruto':
                    result = await mumaker.ephoto("https://en.ephoto360.com/naruto-shippuden-logo-style-text-effect-online-808.html", [text]);
                    break;
                case 'dragonball':
                    result = await mumaker.ephoto("https://ephoto360.com/tao-hieu-ung-chu-phong-cach-dragon-ball-truc-tuyen-1000.html", [text]);
                    break;
                default:
                    return await sock.sendMessage(chatId, messageTemplates.error("Invalid text generator type"));
            }

            if (!result || !result.image) {
                throw new Error('No image URL received from the API');
            }

            await sock.sendMessage(chatId, messageTemplates.success(text, result.image));
        } catch (error) {
            console.error('Error in text generator:', error);
            await sock.sendMessage(chatId, messageTemplates.error(`Error: ${error.message}`));
        }
    } catch (error) {
        console.error('Error in textmaker command:', error);
        await sock.sendMessage(chatId, messageTemplates.error("An error occurred. Please try again later."));
    }
}

module.exports = textmakerCommand;